// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// knapsack_adaptive_Rcpp
List knapsack_adaptive_Rcpp(NumericVector w, NumericVector v, double W, double k_lo, double k_hi, int warmup);
RcppExport SEXP _sacADos_knapsack_adaptive_Rcpp(SEXP wSEXP, SEXP vSEXP, SEXP WSEXP, SEXP k_loSEXP, SEXP k_hiSEXP, SEXP warmupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type k_lo(k_loSEXP);
    Rcpp::traits::input_parameter< double >::type k_hi(k_hiSEXP);
    Rcpp::traits::input_parameter< int >::type warmup(warmupSEXP);
    rcpp_result_gen = Rcpp::wrap(knapsack_adaptive_Rcpp(w, v, W, k_lo, k_hi, warmup));
    return rcpp_result_gen;
END_RCPP
}
// knapsack_dp_Rcpp
List knapsack_dp_Rcpp(int W, IntegerVector w, NumericVector v);
RcppExport SEXP _sacADos_knapsack_dp_Rcpp(SEXP WSEXP, SEXP wSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type W(WSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(knapsack_dp_Rcpp(W, w, v));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sacADos_knapsack_adaptive_Rcpp", (DL_FUNC) &_sacADos_knapsack_adaptive_Rcpp, 6},
    {"_sacADos_knapsack_dp_Rcpp", (DL_FUNC) &_sacADos_knapsack_dp_Rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_sacADos(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
