# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Self-tuning online knapsack heuristic (C++ / Rcpp)
#'
#' C++ port of knapsack_adaptive. Single pass, O(n).
#' See knapsack_adaptive for the full description of the algorithm.
#'
#' @param w Weights (arrival order).
#' @param v Values (arrival order).
#' @param W Capacity.
#' @param k_lo Selectivity for uncorrelated case (default 4).
#' @param k_hi Selectivity for perfectly correlated case (default 30).
#' @param warmup Items used to estimate L, U (-1 = auto).
#' @return List with value, selected (1-based), used_weight.
#' @examples
#' inst <- generate_knapsack(200, type = "uncorrelated")
#' knapsack_adaptive_Rcpp(inst$w, inst$v, inst$W)$value
#' @export
knapsack_adaptive_Rcpp <- function(w, v, W, k_lo = 4.0, k_hi = 30.0, warmup = -1L) {
    .Call(`_sacADos_knapsack_adaptive_Rcpp`, w, v, W, k_lo, k_hi, warmup)
}

#' DP solver for the 0-1 knapsack (C++ / Rcpp)
#'
#' Same algorithm as knapsack_dp but in C++. O(n*W) time and space.
#' Used for the R-vs-C++ speed comparison.
#'
#' @param W Capacity.
#' @param w Integer vector of weights.
#' @param v Numeric vector of values.
#' @return List with value and selected (1-based indices).
#' @examples
#' inst <- generate_knapsack(20, type = "uncorrelated")
#' knapsack_dp_Rcpp(inst$W, inst$w, inst$v)
#' @export
knapsack_dp_Rcpp <- function(W, w, v) {
    .Call(`_sacADos_knapsack_dp_Rcpp`, W, w, v)
}
